### ISSUE TITLE
'oboe/oboe.h' file not found

### ISSUE THREAD

**Issue by meticulo3366** [appneta/node-traceview#119]
when performing the following command 

` npm install --save traceview`

I ran into the following issue

> node-gyp rebuild
>
>  CXX(target) Release/obj.target/traceview-bindings/src/bindings.o
>In file included from ../src/bindings.cc:1:
>../src/bindings.h:12:10: fatal error: 'oboe/oboe.h' file not found
>>#include <oboe/oboe.h>
         ^
>1 error generated.
>make: *** [Release/obj.target/traceview-bindings/src/bindings.o] Error 1
>gyp ERR! build error 
>gyp ERR! stack Error: `make` failed with exit code: 2
>gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node->gyp/lib/build.js:270:23)
>gyp ERR! stack     at emitTwo (events.js:87:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
>gyp ERR! System Darwin 14.5.0
>gyp ERR! command "/usr/local/Cellar/node/4.1.2/bin/node" >"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /Users/zeke/MAVRCK/code/fan-grader->js/grader/node_modules/traceview/node_modules/traceview-bindings
>gyp ERR! node -v v4.1.2
>gyp ERR! node-gyp -v v3.0.3
>gyp ERR! not ok 
>npm WARN optional dep failed, continuing traceview-bindings@1.0.3

details about my environment

`node --version` = `v4.1.2`
`npm  --version` = `2.14.6`

what is the work around for this problem?

**Comment by Qard** [comment]
You need to have liboboe installed, which is provided by the tracelyzer package in the "getting started" process of setting up a traceview account.

For OSes that don't support installing tracelyzer, that warning will be emitted. Note that it is a warning, not an error--the `npm WARN` bit at the end is the important bit. Unfortunately, I don't have much control over what gyp spits out when attempting the build.

**Comment by Qard** [comment]
Ok, I've worked out a way around this. I need to short-circuit the normal node-gyp build process in npm to replace it with my own. I'll get a fix out soon. :smiley_cat:

**Comment by Qard** [comment]
This is fixed in `traceview-bindings` 1.0.6.
