### ISSUE TITLE
Review whether to include Locals with the express rendering events

### ISSUE THREAD

**Issue by MikeA-** [appneta/node-traceview#20]
A couple of concerns:  Locals can be very large, and could contain sensitive data.

We could truncate Locals at some threshold (maybe 100 chars) and also tie into the privacy flag that can be used to skip reporting query parameters (or maybe introduce a new privacy flag for locals)

**Comment by Qard** [comment]
Seems like this is probably not going to happen anytime soon, unless someone actually asks for it, so I'm closing this.
